final doctorMapList = [
  {
    "name": "Mr. Aman Deshmukh",
    "type": "Therapist",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/doctor.png",
    "description": "Money cannot buy happiness, but it can pay for therapy.",
  },
  {
    "name": "Mr. Bhagat Kamra",
    "type": "Psychologist",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/doctor.png",
    "description": "Money cannot buy happiness, but it can pay for therapy.",
  },
  {
    "name": "Mr. Sonu Chaudhary",
    "type": "Therapist",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image":"assets/doctor.png",
    "description": "Money cannot buy happiness, but it can pay for therapy.",
  },
  {
    "name": "Dr. Rahul Pardeshi",
    "type": "Psychiatrist",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image":"assets/doctor.png",
    "description": "Money cannot buy happiness, but it can pay for therapy.",
  }
];
